const KEY='scrabble-note-v2';
const LEGACY_KEY='scrabble-note-v1';
const BACKUP_KEY='scrabble-note-auto-backup';
const now=()=>new Date().toISOString();
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=dateKey(new Date());
const demo={notes:[{id:uid(),title:'Scrabble — Useful 7 Letter Words',body:'Example notes\n\n• words that use common hooks\n• keep difficult anagrams here\n• add meanings and mnemonics',tags:['scrabble','7-letter'],favorite:true,deleted:false,created:now(),updated:now()},{id:uid(),title:'Q / Z / X Words',body:'Q words:\n- QUEEN\n- QUA...\n\nAdd your own discoveries while studying.',tags:['letters'],favorite:false,deleted:false,created:now(),updated:now()}],words:[{word:'QUEEN',meaning:'ราชินี',score:14,tags:'Q'},{word:'QUIZ',meaning:'แบบทดสอบ',score:23,tags:'Q Z'},{word:'JAZZ',meaning:'ดนตรีแจ๊ซ',score:29,tags:'J Z'},{word:'OX',meaning:'วัวตัวผู้',score:9,tags:'X'},{word:'BOX',meaning:'กล่อง',score:12,tags:'X'}],tasks:[{id:uid(),date:today,text:'ทบทวนคำ 20 คำ',done:false},{id:uid(),date:dateKey(Date.now()+864e5),text:'เพิ่มคำศัพท์ Q / Z',done:false}],events:[{id:uid(),date:today,time:'19:00',title:'ฝึกศัพท์ Scrabble',type:'Practice',noteId:null} ]};
// Safe migration: keep the old v1 data and merge it into v2 instead of replacing it.
const parseJSON=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const legacy=parseJSON(LEGACY_KEY);
let state=parseJSON(KEY)||demo;
if(legacy){
  // Preserve an untouched copy before any migration work.
  try{localStorage.setItem('scrabble-note-v1-backup',JSON.stringify(legacy))}catch{}
  state={...state,
    notes:Array.isArray(legacy.notes)?legacy.notes:[...(state.notes||[])],
    words:Array.isArray(legacy.words)?legacy.words:[...(state.words||[])],
    tasks:Array.isArray(legacy.tasks)?legacy.tasks:[...(state.tasks||[])],
    events:Array.isArray(legacy.events)?legacy.events:[...(state.events||[])]
  };
  // Avoid duplicate records if a previous migration already copied some items.
  state.notes=[...new Map(state.notes.map(x=>[x.id,x])).values()];
  state.words=[...new Map(state.words.map((x,i)=>[x.word+'|'+i,x])).values()];
  state.tasks=[...new Map(state.tasks.map(x=>[x.id,x])).values()];
  state.events=[...new Map(state.events.map(x=>[x.id,x])).values()];
  localStorage.setItem(KEY,JSON.stringify(state));
  localStorage.setItem('scrabble-note-migrated','true');
}
state.notes??=[];state.words??=[];state.tasks??=[];state.events??=[];
state.tasks=state.tasks.map(t=>({...t,id:t.id||uid()}));state.events=state.events.map(e=>({...e,id:e.id||uid()}));
let selected=state.notes.find(n=>!n.deleted)?.id||null,view='notes',filter='all',query='',calMode='month',calDate=new Date();
let backupTimer;
const save=()=>{
  const data=JSON.stringify(state);
  localStorage.setItem(KEY,data);
  clearTimeout(backupTimer);
  backupTimer=setTimeout(()=>{try{localStorage.setItem(BACKUP_KEY,JSON.stringify({savedAt:now(),state}))}catch{}},350);
  const el=document.querySelector('#saveState');if(el)el.textContent='Saved • '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});
};
const toast=s=>{const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1500)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function renderNotes(){const list=document.querySelector('#noteList');let ns=state.notes.filter(n=>!n.deleted&&(filter==='all'||n.tags.includes(filter))&&(n.title+' '+n.body+' '+n.tags.join(' ')).toLowerCase().includes(query.toLowerCase()));const sort=document.querySelector('#sortSelect').value;ns.sort((a,b)=>sort==='az'?a.title.localeCompare(b.title):sort==='created'?b.created.localeCompare(a.created):b.updated.localeCompare(a.updated));list.innerHTML=ns.map(n=>`<div class="note-card ${n.id===selected?'selected':''}" data-id="${n.id}"><h3>${n.favorite?'☆ ':''}${esc(n.title||'Untitled')}</h3><p>${esc(n.body.replace(/\n/g,' '))}</p><div class="meta">${new Date(n.updated).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'})}</div></div>`).join('')||'<div class="empty-list">ยังไม่มีโน้ต</div>';list.querySelectorAll('.note-card').forEach(x=>x.onclick=()=>{selected=x.dataset.id;renderNotes();renderEditor()});const tags=[...new Set(state.notes.filter(n=>!n.deleted).flatMap(n=>n.tags))];document.querySelector('#tagFilters').innerHTML='<button class="chip '+(filter==='all'?'active':'')+'" data-tag="all">All</button>'+tags.map(t=>`<button class="chip ${filter===t?'active':''}" data-tag="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('[data-tag]').forEach(x=>x.onclick=()=>{filter=x.dataset.tag;renderNotes()})}
function renderEditor(){const n=state.notes.find(x=>x.id===selected&&!x.deleted),e=document.querySelector('#editor');if(!n){e.innerHTML='<div class="empty-editor">เลือกโน้ตเพื่อเริ่มจด หรือกด <b>New Note</b></div>';return}const linked=state.events.filter(x=>x.noteId===n.id);e.innerHTML=`<div class="editor-head"><input class="title-input" id="title" value="${esc(n.title)}"><button class="icon-btn" id="fav">${n.favorite?'★':'☆'}</button><button class="icon-btn" id="del">⌫</button></div><div class="editor-body"><textarea id="body" placeholder="Start writing...">${esc(n.body)}</textarea></div><div class="editor-foot"><div>Tags: <input class="tag-input" id="tags" value="${esc(n.tags.join(', '))}" placeholder="scrabble, hooks, Q"></div><div class="quick-actions"><button class="quick-btn" id="scheduleNote">＋ Calendar</button><button class="quick-btn" id="duplicateNote">⧉</button><span>${linked.length} linked event${linked.length===1?'':'s'} • Autosave</span></div></div>`;const update=()=>{n.title=document.querySelector('#title').value;n.body=document.querySelector('#body').value;n.tags=document.querySelector('#tags').value.split(',').map(x=>x.trim()).filter(Boolean);n.updated=now();save();renderNotes()};['title','body','tags'].forEach(id=>document.querySelector('#'+id).addEventListener('input',()=>{clearTimeout(window.st);window.st=setTimeout(update,250)}));document.querySelector('#fav').onclick=()=>{n.favorite=!n.favorite;save();renderEditor();renderNotes()};document.querySelector('#del').onclick=()=>{n.deleted=true;selected=state.notes.find(x=>!x.deleted)?.id||null;save();renderNotes();renderEditor();toast('Moved to Trash')};document.querySelector('#duplicateNote').onclick=()=>{const copy={...n,id:uid(),title:(n.title||'Untitled')+' (Copy)',created:now(),updated:now(),tags:[...n.tags]};state.notes.unshift(copy);selected=copy.id;save();renderNotes();renderEditor();toast('Duplicated note')};document.querySelector('#scheduleNote').onclick=()=>{addEvent(n.id)} }
function newNote(){const n={id:uid(),title:'Untitled Note',body:'',tags:[],favorite:false,deleted:false,created:now(),updated:now()};state.notes.unshift(n);selected=n.id;save();switchView('notes');setTimeout(()=>document.querySelector('#title')?.focus(),50)}
function renderWords(){let ws=state.words.filter(w=>(w.word+' '+w.meaning+' '+w.tags).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.word.localeCompare(b.word));document.querySelector('#wordCount').textContent=state.words.length;document.querySelector('#letterCount').textContent=state.words.reduce((a,w)=>a+w.word.length,0);document.querySelector('#pointsCount').textContent=state.words.reduce((a,w)=>a+(Number(w.score)||0),0);document.querySelector('#wordTable').innerHTML='<div class="word-row head"><span>WORD</span><span>MEANING</span><span>POINTS</span><span>TAGS</span><span></span></div>'+ws.map(w=>`<div class="word-row"><span class="word">${esc(w.word)}</span><span>${esc(w.meaning)}</span><span class="score">${w.score}</span><span>${esc(w.tags)}</span><button onclick="removeWord(${state.words.indexOf(w)})">×</button></div>`).join('')}
window.removeWord=i=>{state.words.splice(i,1);save();renderWords()};
function addWord(){let word=prompt('Word (ตัวพิมพ์ใหญ่):');if(!word)return;word=word.trim().toUpperCase();let meaning=prompt('Meaning / ความหมาย:')||'';let score=prompt('Tile points:','0');state.words.push({word,meaning,score:Number(score)||0,tags:''});save();renderWords();toast('Added word')}
function addTask(date=today){const text=prompt('Task:');if(!text)return;const d=prompt('Date (YYYY-MM-DD):',date)||date;if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return toast('รูปแบบวันที่ไม่ถูกต้อง');state.tasks.push({id:uid(),date:d,text:text.trim(),done:false});save();renderCalendar();renderDayPanel(d);toast('เพิ่ม Task แล้ว')}
function addEvent(noteId=null,date=dateKey(calDate)){const title=prompt('Event name:');if(!title)return;const d=prompt('Date (YYYY-MM-DD):',date)||date;const time=prompt('Time (HH:MM):','19:00')||'';const type=prompt('Category:','Practice')||'Other';state.events.push({id:uid(),date:d,time,title:title.trim(),type,noteId});save();renderCalendar();renderDayPanel(d);toast('เพิ่ม Event แล้ว')}
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
function fmt(d,opt){return new Intl.DateTimeFormat('th-TH',opt).format(d)}
function renderDashboard(){const tasksToday=state.tasks.filter(t=>t.date===today),done=tasksToday.filter(t=>t.done).length,events=state.events.filter(e=>e.date===today);const streak=new Set([...state.tasks.filter(t=>t.done).map(t=>t.date),...state.events.map(e=>e.date)]);let s=0,d=new Date();while(streak.has(dateKey(d))){s++;d.setDate(d.getDate()-1)}document.querySelector('#dashboard').innerHTML=`<div><b>${tasksToday.length}</b><span>Today tasks</span><small>${done} done</small></div><div><b>${events.length}</b><span>Today's events</span><small>next: ${events[0]?.time||'—'}</small></div><div><b>${s}</b><span>Activity streak</span><small>days active</small></div><div><b>${state.notes.filter(n=>!n.deleted).length}</b><span>Notes</span><small>${state.words.length} words</small></div>`}
function itemsForDate(d){return [...state.events.filter(e=>e.date===d).map(e=>({kind:'event',...e})),...state.tasks.filter(t=>t.date===d).map(t=>({kind:'task',...t}))].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
function renderCalendar(){renderDashboard();const c=document.querySelector('#calendar');if(calMode==='month')renderMonth(c);else if(calMode==='week')renderWeek(c);else renderDay(c);document.querySelectorAll('.cal-date').forEach(x=>x.onclick=()=>{calDate=new Date(x.dataset.date+'T12:00:00');renderCalendar();renderDayPanel(x.dataset.date)});document.querySelector('#periodLabel').textContent=calMode==='month'?fmt(calDate,{month:'long',year:'numeric'}):calMode==='week'?`${fmt(startOfWeek(calDate),{day:'numeric',month:'short'})} – ${fmt(new Date(startOfWeek(calDate).getTime()+6*864e5),{day:'numeric',month:'short',year:'numeric'})}`:fmt(calDate,{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderDayPanel(dateKey(calDate))}
function cell(d){const dk=dateKey(d),its=itemsForDate(d);return `<div class="cal-cell ${dk===today?'today':''} ${dk===dateKey(calDate)?'chosen':''}"><button class="cal-date" data-date="${dk}">${d.getDate()}</button><div class="cell-items">${its.slice(0,4).map(i=>`<div class="cal-item ${i.kind} ${i.done?'done':''}">${i.kind==='event'?'●':'☐'} ${esc(i.time?i.time+' ':'')}${esc(i.title||i.text)}</div>`).join('')}${its.length>4?`<small>+${its.length-4} more</small>`:''}</div></div>`}
function renderMonth(c){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));c.innerHTML='<div class="weekday-row">'+['จ','อ','พ','พฤ','ศ','ส','อา'].map(x=>`<span>${x}</span>`).join('')+'</div><div class="month-grid">'+Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return cell(d)}).join('')+'</div>'}
function renderWeek(c){const s=startOfWeek(calDate);c.innerHTML='<div class="week-grid">'+Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return `<div class="week-col"><div class="week-head">${fmt(d,{weekday:'short'})}<b>${d.getDate()}</b></div>${itemsForDate(dateKey(d)).map(()=> '').join('')}${itemsForDate(d).map(it=>`<div class="week-item ${it.kind} ${it.done?'done':''}"><b>${esc(it.time||'')}</b> ${esc(it.title||it.text)}</div>`).join('')||'<span class="muted">ว่าง</span>'}<button class="tiny-add" data-date="${dateKey(d)}">＋</button></div>`}).join('')+'</div>';c.querySelectorAll('.tiny-add').forEach(b=>b.onclick=()=>addEvent(null,b.dataset.date))}
function renderDay(c){const d=calDate,its=itemsForDate(d);c.innerHTML=`<div class="day-view"><h3>${fmt(d,{weekday:'long',day:'numeric',month:'long'})}</h3>${its.map(it=>`<div class="day-item ${it.kind}"><b>${it.kind==='event'?(it.time||''):'TASK'}</b><span>${esc(it.title||it.text)}</span>${it.kind==='task'?`<input type="checkbox" ${it.done?'checked':''} onchange="toggleTask('${it.id}')">`:''}</div>`).join('')||'<div class="muted">ไม่มีรายการวันนี้</div>'}</div>`}
function renderDayPanel(d){const p=document.querySelector('#dayPanel'),its=itemsForDate(d),notes=state.notes.filter(n=>!n.deleted);p.innerHTML=`<div class="day-panel-head"><div><h3>${fmt(new Date(d+'T12:00:00'),{weekday:'long',day:'numeric',month:'long'})}</h3><small>${its.length} รายการ</small></div><button class="mini-btn" id="panelAdd">＋ เพิ่ม</button></div><div class="quick-summary"><b>${state.tasks.filter(t=>t.date===d&&t.done).length}/${state.tasks.filter(t=>t.date===d).length}</b><span>tasks done</span></div>${its.map(i=>`<div class="panel-item ${i.kind}"><div><b>${i.kind==='event'?(i.time||''):'☐'}</b><span>${esc(i.title||i.text)}</span></div>${i.kind==='task'?`<button onclick="toggleTask('${i.id}')">${i.done?'↩':'✓'}</button>`:`<button onclick="deleteEvent('${i.id}')">×</button>`}</div>`).join('')||'<div class="muted">ยังไม่มี Event หรือ Task</div>'}<div class="panel-links"><b>Notes</b>${notes.slice(0,5).map(n=>`<button onclick="openNote('${n.id}')">${esc(n.title)}</button>`).join('')||'<span class="muted">ไม่มีโน้ต</span>'}</div>`;document.querySelector('#panelAdd').onclick=()=>addEvent(null,d)}
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);if(t)t.done=!t.done;save();renderCalendar();renderDayPanel(t?.date||today)};window.deleteEvent=id=>{const e=state.events.find(x=>x.id===id),d=e?.date;state.events=state.events.filter(x=>x.id!==id);save();renderCalendar();renderDayPanel(d||today);toast('ลบ Event แล้ว')};
function renderGrid(target,deleted=false){const ns=state.notes.filter(n=>n.deleted===deleted&&(!deleted?n.favorite:true));document.querySelector(target).innerHTML=ns.map(n=>`<div class="grid-card"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><button onclick="openNote('${n.id}')">Open</button>${deleted?`<button onclick="restore('${n.id}')">Restore</button><button onclick="purge('${n.id}')">Delete forever</button>`:''}</div>`).join('')||'<div class="muted">ไม่มีรายการ</div>'}
window.openNote=id=>{selected=id;switchView('notes');renderNotes();renderEditor()};window.restore=id=>{const n=state.notes.find(x=>x.id===id);n.deleted=false;n.updated=now();save();renderGrid('#trashList',true)};window.purge=id=>{state.notes=state.notes.filter(x=>x.id!==id);save();renderGrid('#trashList',true)};
function switchView(v){view=v;document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.querySelector('#'+v+'View').classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const names={notes:['Notes','Capture words, ideas and game notes.'],words:['Word Bank','คลังคำศัพท์สำหรับ Scrabble'],planner:['Calendar','Calendar + Planner + Notes'],favorites:['Favorites','โน้ตที่ปักหมุดไว้'],trash:['Trash','โน้ตที่ลบแล้ว']};document.querySelector('#viewTitle').textContent=names[v][0];document.querySelector('#viewSub').textContent=names[v][1];if(v==='notes'){renderNotes();renderEditor()}if(v==='words')renderWords();if(v==='planner')renderCalendar();if(v==='favorites')renderGrid('#favoriteList');if(v==='trash')renderGrid('#trashList',true)}
function initSplit(){const layout=document.querySelector('#notesLayout'),divider=document.querySelector('#splitDivider');const saved=Number(localStorage.getItem('scrabble-list-width')||300);layout.style.setProperty('--list-width',Math.max(190,Math.min(520,saved))+'px');let drag=false;divider.addEventListener('pointerdown',e=>{drag=true;divider.setPointerCapture?.(e.pointerId)});divider.addEventListener('pointermove',e=>{if(!drag)return;const r=layout.getBoundingClientRect(),w=Math.max(190,Math.min(520,e.clientX-r.left));layout.style.setProperty('--list-width',w+'px');localStorage.setItem('scrabble-list-width',w)});divider.addEventListener('pointerup',()=>drag=false);document.querySelector('#listWidthBtn').onclick=()=>{const w=parseInt(getComputedStyle(layout).getPropertyValue('--list-width'))||300,next=w<280?380:w<360?450:240;layout.style.setProperty('--list-width',next+'px');localStorage.setItem('scrabble-list-width',next);toast('ปรับสัดส่วน 2 จอ')};document.querySelector('#listCollapseBtn').onclick=()=>{layout.classList.toggle('list-collapsed');document.querySelector('#listCollapseBtn').textContent=layout.classList.contains('list-collapsed')?'› รายการ':'‹ รายการ'};document.querySelector('#splitBtn').onclick=()=>{layout.classList.toggle('list-collapsed');document.querySelector('#listCollapseBtn').textContent=layout.classList.contains('list-collapsed')?'› รายการ':'‹ รายการ'};document.querySelector('#focusBtn').onclick=()=>{document.body.classList.toggle('focus-mode');document.querySelector('#focusBtn span').textContent=document.body.classList.contains('focus-mode')?'ออก':'เขียน'} }
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>switchView(x.dataset.view));document.querySelector('#newNote').onclick=newNote;document.querySelector('#addWord').onclick=addWord;document.querySelector('#addTask').onclick=()=>addTask();document.querySelector('#addEvent').onclick=()=>addEvent();document.querySelector('#todayBtn').onclick=()=>{calDate=new Date();renderCalendar()};document.querySelector('#prevPeriod').onclick=()=>{if(calMode==='month')calDate.setMonth(calDate.getMonth()-1);else if(calMode==='week')calDate.setDate(calDate.getDate()-7);else calDate.setDate(calDate.getDate()-1);renderCalendar()};document.querySelector('#nextPeriod').onclick=()=>{if(calMode==='month')calDate.setMonth(calDate.getMonth()+1);else if(calMode==='week')calDate.setDate(calDate.getDate()+7);else calDate.setDate(calDate.getDate()+1);renderCalendar()};document.querySelectorAll('.cal-view').forEach(b=>b.onclick=()=>{calMode=b.dataset.cal;document.querySelectorAll('.cal-view').forEach(x=>x.classList.toggle('active',x===b));renderCalendar()});document.querySelector('#sortSelect').onchange=renderNotes;document.querySelector('#globalSearch').oninput=e=>{query=e.target.value;if(view==='notes')renderNotes();if(view==='words')renderWords();if(view==='planner')renderCalendar()};document.querySelector('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='scrabble-note-backup.json';a.click();toast('Exported backup')};document.querySelector('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{
  const incoming=JSON.parse(r.result); if(!incoming||typeof incoming!=='object')throw 0;
  // Keep current data as an automatic rollback before importing.
  localStorage.setItem('scrabble-note-before-import',JSON.stringify({savedAt:now(),state}));
  state={...state,
    notes:[...(state.notes||[]),...(incoming.notes||[])],words:[...(state.words||[]),...(incoming.words||[])],
    tasks:[...(state.tasks||[]),...(incoming.tasks||[])],events:[...(state.events||[]),...(incoming.events||[])]};
  state.notes=[...new Map(state.notes.map(x=>[x.id,x])).values()];
  state.tasks=[...new Map(state.tasks.map(x=>[x.id,x])).values()];
  state.events=[...new Map(state.events.map(x=>[x.id,x])).values()];
  state.words=[...new Map(state.words.map(x=>[(x.word||'')+'|'+JSON.stringify(x),x])).values()];
  selected=state.notes.find(n=>!n.deleted)?.id||null;save();switchView('notes');toast('Imported + existing data kept');
}catch{toast('Invalid JSON')}};r.readAsText(f)};document.querySelector('#clearBtn').onclick=()=>{if(confirm('Reset current data? A backup will be kept first.')){try{localStorage.setItem('scrabble-note-before-reset',JSON.stringify({savedAt:now(),state}))}catch{}state=JSON.parse(JSON.stringify(demo));selected=state.notes[0].id;save();switchView('notes');toast('Reset complete • backup kept')}};document.querySelector('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('scrabble-dark',document.body.classList.contains('dark'))};if(localStorage.getItem('scrabble-dark')==='true')document.body.classList.add('dark');initSplit();save();switchView('notes');
